<?php

    return [
        'account' =>
            [
                'title'                     => 'My account',
                'current_password_invalid'  => 'Your current password is invalid.',
                'updated'                   => 'Account updated.',
                'username'                  => 'Username',
                'email'                     => 'Email address',
                'current_password'          => 'Current password',
                'new_password'              => 'New password',
                'new_password_confirmation' => 'Confirm new password',
                'save'                      => 'Save',
                'delete'                    => 'Delete your account',
                'delete_confirmation'       => 'Are you sure you want to delete your account from :site? This cannot be undone.',
                'deletion_warning'          => 'Warning: This action cannot be undone! All data associated with your account
            will be permanently removed from this website.',
                'type'                      => 'Account type',
                'created_at'                => 'Account created on',
                'last_login'                => 'Last login',
                'last_login_from'           => ':timestamp from :ip',
                '2fa'                       =>
                    [
                        'disable'              => 'Disable',
                        'disable_warning'      => 'To re-enable two-factor-authentication, you will have to set up all of your authentication apps again',
                        'disabled'             => 'Two-factor-authentication is currently disabled. Enable this to better secure access to your account. Using this it will be only possible to log in to your account using your login credentials and a special code that changes every 30 seconds. This code is generated by an application on a mobile device. This can be used free of charge.',
                        'enable'               => 'Enable',
                        'enabled'              => 'Two-factor-authentication is currently enabled. Your account is secured sufficiently.',
                        'has_been_disabled'    => 'Two-factor-authentication has been disabled',
                        'instructions'         => 'Scan the QR-code using an authentication application on a mobile device in order to receive the temporary access code. This code changes every 30 seconds. When you have scanned the QR-code, enter the generated code and press validate.
Well known authentication apps are OTP Auth for iOS, Google Authenticator for Android and Authenticator for Windows Phone.',
                        'invalid_key'          => 'Invalid code',
                        'key'                  => 'Code',
                        'missing_key'          => 'Code missing',
                        'missing_secret'       => 'Secret token is missing in request',
                        'off'                  => 'Off',
                        'on'                   => 'On',
                        'success'              => 'Two-factor-authentication has been enabled',
                        'success_instructions' => 'Two-factor-authentication has successfully enabled for your account. You may scan the QR-code if you use multiple authentication applications or devices.',
                        'title'                => 'Two-factor-authentication',
                        'validate'             => 'Validate',
                    ],
                'errors_occurred'           => 'An error has occurred. Please correct this error.|Errors have occurred, please correct these errors.',
            ],
        'rank'    =>
            [
                'member' => 'User',
                'admin'  => 'Administrator',
            ],
    ];
